repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: detect-private-key
      - id: check-added-large-files
        exclude: ^target/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [ --fix ]
        entry: 'ruff check'
        files: ^(src|tests)/
      - id: ruff-format
        files: ^(src|tests)/

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: python
        language_version: python3.12
        args: [
          '--config-file=mypy.ini'
        ]
        files: ^(src|tests)/
        types_or: [python]
        entry: 'mypy'
