"""empty message

Revision ID: 1fa205681f82
Revises: 63f85094d1dd
Create Date: 2025-05-28 14:59:11.130155

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1fa205681f82"
down_revision: str | None = "63f85094d1dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
