"""empty message

Revision ID: 32da4148f3ae
Revises: e1ceae041d4d
Create Date: 2025-05-27 12:14:33.224296

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "32da4148f3ae"
down_revision: str | None = "e1ceae041d4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
