"""empty message

Revision ID: 63f85094d1dd
Revises: 32da4148f3ae
Create Date: 2025-05-28 14:40:19.553483

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "63f85094d1dd"
down_revision: str | None = "32da4148f3ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_reports",
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("report_name", sa.Text(), nullable=False),
        sa.Column("creator_id", sa.UUID(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("device_type", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("report_id"),
    )
    op.drop_table("device_report")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_report",
        sa.Column("report_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("report_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("creator_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("comment", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("device_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("device_type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("report_id", name="device_report_pkey"),
    )
    op.drop_table("device_reports")
    # ### end Alembic commands ###
