"""empty message

Revision ID: 95b6683dce93
Revises: b92550d32707
Create Date: 2025-05-28 21:37:37.903126

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "95b6683dce93"
down_revision: str | None = "b92550d32707"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
