"""empty message

Revision ID: b92550d32707
Revises: 1fa205681f82
Create Date: 2025-05-28 21:16:06.343149

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b92550d32707"
down_revision: str | None = "1fa205681f82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
