"""empty message

Revision ID: e1ceae041d4d
Revises:
Create Date: 2025-05-26 12:53:41.361172

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1ceae041d4d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_report",
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("report_name", sa.Text(), nullable=False),
        sa.Column("creator_id", sa.UUID(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("device_type", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("report_id"),
    )
    op.create_table(
        "outbox",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("data", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("message_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outbox")
    op.drop_table("device_report")
    # ### end Alembic commands ###
